### PR TITLE
fixed set-key call

### PR DESCRIPTION
**Pull request by saikyun**
just changed the call to set-key :)

### CODE REVIEW

**Comment by sogaiu** [comment]
That is a commented out form that I'm not sure I will retain.

You probably noticed I had a comment there about `set-key` too :)

**Comment by saikyun** [comment]
Oh okay, but I changed the non-commented out part too. :) You don't have to
use it ofc.

Den ons 23 feb. 2022 15:21sogaiu ***@***.***> skrev:

**Comment by sogaiu** [comment]
Ah I think I missed the `:tab` related changes.  I've fixed that in 47f2f4bebfdc4ca73cfe82877b41be764b46c4f8

Thanks!

**Comment by saikyun** [comment]
Okay, nice. :)

**Pull request closed without merging**
